<a href="https://colab.research.google.com/github/usnhee/TIL-/blob/master/NaiveBayes_DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
data = pd.read_csv('weather.csv', sep=',')

In [2]:
data

outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [17]:
from sklearn.naive_bayes import MultinomialNB
multinomial_model = MultinomialNB()
multinomial_model

MultinomialNB()

In [18]:
# mapping directory 만들기 
outlook_dic={'overcast':0,'rainy':1,'sunny':2}
temperature_dic={'cool':0,'hot':1,'mild':2}
humidity_dic = {'high':0,'normal':1}
windy_dic = {False:0,True:1}

In [19]:
# 딕셔너리 활용해 데이터 매핑
data['outlook'] = data['outlook'].map(outlook_dic)
data['temperature'] = data['temperature'].map(temperature_dic)
data['humidity']=data['humidity'].map(humidity_dic)
data['windy']=data['windy'].map(windy_dic)
data

outlook  temperature  humidity  windy play
0         0            1         0      0  yes
1         0            0         1      1  yes
2         0            2         0      1  yes
3         0            1         1      0  yes
4         1            2         0      0  yes
5         1            0         1      0  yes
6         1            0         1      1   no
7         1            2         1      0  yes
8         1            2         0      1   no
9         2            1         0      0   no
10        2            1         0      1   no
11        2            2         0      0   no
12        2            0         1      0  yes
13        2            2         1      1  yes

In [20]:
multinomial_model.fit( data.iloc[:, :4], data['play'])

MultinomialNB()

In [21]:
multinomial_model.predict([[1,2,0,1]])
#rainy,mild,high,windy(True)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


array(['yes'], dtype='<U3')

In [22]:
multinomial_model.predict_proba([[2,2,0,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


array([[0.57311795, 0.42688205]])

In [23]:
from sklearn.datasets import load_iris
iris = load_iris()

In [24]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species']=iris.target

In [25]:
iris_df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  species
0                5.1               3.5  ...               0.2        0
1                4.9               3.0  ...               0.2        0
2                4.7               3.2  ...               0.2        0
3                4.6               3.1  ...               0.2        0
4                5.0               3.6  ...               0.2        0

[5 rows x 5 columns]

In [26]:
from sklearn.naive_bayes import GaussianNB
gaussian_model = GaussianNB()

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_df.iloc[:,:4], iris_df['species'], test_size = 0.33)
gaussian_model.fit(X_train, y_train)

GaussianNB()

In [28]:
# 성능평가 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, gaussian_model.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.94      0.94      0.94        18
           2       0.93      0.93      0.93        14

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [29]:
print(confusion_matrix(y_test, gaussian_model.predict(X_test)))

[[18  0  0]
 [ 0 17  1]
 [ 0  1 13]]


In [3]:
import pandas as pd 
data = pd.read_csv('weather.csv', sep = ',')
data

outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [4]:
## mapping dictionary making

outlook_dic = {'overcast':0, 'rainy':1, 'sunny':2}
temperature_dic = {'cool':0, 'hot': 1 , 'mild':2}
humidity_dic = {'high':0, 'normal':1}
windy_dic = {False:0, True:1}


In [5]:
# Mapping data 
data['outlook'] = data['outlook'].map(outlook_dic)
data['temperature'] = data['temperature'].map(temperature_dic)
data['humidity'] = data['humidity'].map(humidity_dic)
data['windy'] = data['windy'].map(windy_dic)
data

outlook  temperature  humidity  windy play
0         0            1         0      0  yes
1         0            0         1      1  yes
2         0            2         0      1  yes
3         0            1         1      0  yes
4         1            2         0      0  yes
5         1            0         1      0  yes
6         1            0         1      1   no
7         1            2         1      0  yes
8         1            2         0      1   no
9         2            1         0      0   no
10        2            1         0      1   no
11        2            2         0      0   no
12        2            0         1      0  yes
13        2            2         1      1  yes

In [6]:
# DecisionTree classiier instance creation

from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf

DecisionTreeClassifier()

In [7]:
clf.fit(data.iloc[:,:4], data['play'])


DecisionTreeClassifier()

In [9]:
## prediction - play or not? 
clf.predict([[2,2,0,1]])
#sunny,mild,high,windy => no 

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['no'], dtype=object)

In [10]:
clf.predict([[1,2,0,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['no'], dtype=object)

In [11]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
%matplotlib inline

In [14]:
data = pd.read_csv('Fish.csv', sep = ',')
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [16]:
X = data[['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width']]
y= data['Species']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
print('train data 수 : ', X_train.shape)
print('test data 수 : ', X_test.shape)

train data 수 :  (106, 6)
test data 수 :  (53, 6)


In [17]:
## 모델 객체 생성(k=5) + 학습
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [19]:
# 모델 정확도 테스트 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,knn.predict(X_test)))

              precision    recall  f1-score   support

       Bream       0.47      0.50      0.48        14
      Parkki       0.25      0.25      0.25         4
       Perch       0.32      0.57      0.41        14
        Pike       0.00      0.00      0.00         5
       Roach       1.00      0.11      0.20         9
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         2

    accuracy                           0.42        53
   macro avg       0.43      0.35      0.33        53
weighted avg       0.49      0.42      0.38        53



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
print(confusion_matrix(y_test, knn.predict(X_test)))

[[10  0  1  0  0  0  0]
 [ 0  4  0  0  0  0  0]
 [ 2  0 14  0  0  0  0]
 [ 3  0  4  4  0  0  0]
 [ 0  1  4  0  0  1  0]
 [ 0  0  0  0  0  4  0]
 [ 1  0  0  0  0  0  0]]


In [20]:
## 모델 객체 생성(k=7) + 학습
knn1 = KNeighborsClassifier(n_neighbors=7)
knn1.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=7)

In [21]:
# 모델 정확도 테스트 
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,knn1.predict(X_test)))

              precision    recall  f1-score   support

       Bream       0.50      0.43      0.46        14
      Parkki       0.00      0.00      0.00         4
       Perch       0.31      0.57      0.40        14
        Pike       0.00      0.00      0.00         5
       Roach       1.00      0.11      0.20         9
       Smelt       1.00      1.00      1.00         5
   Whitefish       0.00      0.00      0.00         2

    accuracy                           0.38        53
   macro avg       0.40      0.30      0.29        53
weighted avg       0.48      0.38      0.36        53



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [31]:
## 나이브 베이지안으로 분류해보자. 
from sklearn.naive_bayes import GaussianNB
gaussian_model = GaussianNB()

In [25]:
X = data[['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width']]
y= data['Species']

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)


In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33)
gaussian_model.fit(X_train, y_train)

GaussianNB()

In [34]:
print(classification_report(y_test, gaussian_model.predict(X_test)))

              precision    recall  f1-score   support

       Bream       0.80      0.73      0.76        11
      Parkki       0.80      1.00      0.89         4
       Perch       0.30      0.19      0.23        16
        Pike       1.00      0.55      0.71        11
       Roach       0.33      0.83      0.48         6
       Smelt       1.00      1.00      1.00         4
   Whitefish       0.33      1.00      0.50         1

    accuracy                           0.58        53
   macro avg       0.65      0.76      0.65        53
weighted avg       0.64      0.58      0.58        53



In [35]:
print(confusion_matrix(y_test, gaussian_model.predict(X_test)))

[[ 8  1  1  0  0  0  1]
 [ 0  4  0  0  0  0  0]
 [ 2  0  3  0 10  0  1]
 [ 0  0  5  6  0  0  0]
 [ 0  0  1  0  5  0  0]
 [ 0  0  0  0  0  4  0]
 [ 0  0  0  0  0  0  1]]


## Decision Tree 만들기 

In [37]:
data = pd.read_csv('weather.csv', sep = ',')
data

outlook temperature humidity  windy play
0   overcast         hot     high  False  yes
1   overcast        cool   normal   True  yes
2   overcast        mild     high   True  yes
3   overcast         hot   normal  False  yes
4      rainy        mild     high  False  yes
5      rainy        cool   normal  False  yes
6      rainy        cool   normal   True   no
7      rainy        mild   normal  False  yes
8      rainy        mild     high   True   no
9      sunny         hot     high  False   no
10     sunny         hot     high   True   no
11     sunny        mild     high  False   no
12     sunny        cool   normal  False  yes
13     sunny        mild   normal   True  yes

In [38]:
#mapping directory 

outlook_dic = {'overcast':0, 'rainy':1, 'sunny':2}
temperature_dic = {'cool':0, 'hot': 1 , 'mild':2}
humidity_dic = {'high':0, 'normal':1}
windy_dic = {False:0, True:1}

# Mapping data 
data['outlook'] = data['outlook'].map(outlook_dic)
data['temperature'] = data['temperature'].map(temperature_dic)
data['humidity'] = data['humidity'].map(humidity_dic)
data['windy'] = data['windy'].map(windy_dic)
data

outlook  temperature  humidity  windy play
0         0            1         0      0  yes
1         0            0         1      1  yes
2         0            2         0      1  yes
3         0            1         1      0  yes
4         1            2         0      0  yes
5         1            0         1      0  yes
6         1            0         1      1   no
7         1            2         1      0  yes
8         1            2         0      1   no
9         2            1         0      0   no
10        2            1         0      1   no
11        2            2         0      0   no
12        2            0         1      0  yes
13        2            2         1      1  yes

In [39]:
# Decision Tree Classifier instance
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf

DecisionTreeClassifier()

In [40]:
clf.fit(data.iloc[:,:4], data['play'])

DecisionTreeClassifier()

In [41]:
clf.predict([[2,2,0,1]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['no'], dtype=object)

In [42]:
X = data[['outlook', 'temperature', 'humidity', 'windy']]
y= data['play']

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [46]:
tree_model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
tree_model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [47]:
y_hat = tree_model.predict(X_test)

In [49]:
from sklearn import metrics
tree_matrix = metrics.confusion_matrix(y_test, y_hat)
print(tree_matrix)
print('\n')

tree_report = metrics.classification_report(y_test, y_hat)
print(tree_report)

[[1 1]
 [1 2]]


              precision    recall  f1-score   support

          no       0.50      0.50      0.50         2
         yes       0.67      0.67      0.67         3

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5

